### ISSUE TITLE
R Funktions Skript 2

### ISSUE THREAD

**Issue by KathaWes** [Rafexidus/Gruppenarbeit-WA#3]
Hallo,

mir ist gerade noch aufgefallen, dass wir Funktionen-R-Skript 2 noch nicht erstellt haben. Das würde ich gleich machen. Hier würde ich dann die Modusfunktion, die bei b) angewendet wird, reinschreiben. 
Fühlt euch frei, noch Ergänzungen/Anpassungen vorzunehmen, wenn ihr noch etwas ändern möchtet.

**Comment by Pglpizzi** [comment]
Sieht gut aus.
Ich würde dann die Funktion aus dem ersten Dokument entfernen, da wir sie dort dann ja nicht mehr brauchen.
