### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by Pglpizzi** [Rafexidus/Gruppenarbeit-WA#4]
Hey,

ich hatte die Tage mal gesehen gehabt, dass wir über den Reiter Settings eine Diskussion starten können, wie es am Ende der Aufgabe auch gefordert war.

Leider finde ich den Reiter (Settings) nicht mehr, vllt. weil ich nicht Ersteller bin oder warum auch immer, aber könnte dann einer von euch die starten.

**Comment by Rafexidus** [comment]
Hey, ich habe jetzt eine Diskussion erstellt. Danke für den Hinweis.
